extends MarginContainer

@export var air_time_text: Label
@export var effective_air_time_text: Label
@export var big_attack_pending_text: Label
@export var is_high_big_attack_text: Label
@export var big_jump_direction_text: Label
@export var dash_attack_direction_text: Label
@export var knockback_velocity_text: Label
@export var knockback_timer_text: Label
@export var attack_count_text: Label
@export var damage_applied_text: Label
@export var velocity_before_attack_text: Label
@export var pending_knockback_text: Label
@export var dash_attack_entities_hit_text: Label
@export var left_wall_text: Label
@export var right_wall_text: Label
@export var ceiling_text: Label
@export var ceiling_2_text: Label
@export var ceiling_3_text: Label
@export var ground_check_text: Label
@export var near_ground_text: Label
@export var near_ground_2_text: Label
@export var near_ground_3_text: Label
@export var jump_count_text: Label
@export var has_double_jump_text: Label
@export var has_triple_jump_text: Label
@export var is_jump_held_text: Label
@export var is_double_jump_held_text: Label
@export var is_triple_jump_held_text: Label
@export var big_jump_timer_text: Label
@export var big_jump_cd_text: Label
@export var dash_timer_text: Label
@export var dash_cd_text: Label
@export var attack_timer_text: Label
@export var attack_cd_text: Label
@export var stun_timer_text: Label
@export var hide_weapon_text: Label
@export var damage_timer_text: Label
@export var invulnerability_text: Label
@export var wall_jump_control_text: Label
@export var attack_area_bodies_text: Label
@export var damage_area_bodies_text: Label
@export var damage_area_monitorable_text: Label
@export var big_attack_area_bodies_text: Label
@export var big_attack_area_2_bodies_text: Label
@export var big_jump_charged_text: Label
@export var can_big_jump_text: Label
@export var can_dash_text: Label
@export var can_wall_jump_text: Label
@export var has_wall_jumped_text: Label
@export var was_on_wall_text: Label
@export var death_animation_played_text: Label
@export var invulnerable_text: Label
@export var state_text: Label
@export var previous_state_text: Label
@export var animation_text: Label
@export var velocity_text: Label
@export var on_floor_text: Label
@export var health_text: Label
@export var stamina_text: Label
@export var stamina_regen_timer_text: Label
